common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from seok.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('seok/', include('seok.urls')),
    path('common/', include('common.urls')),
    path('data/', include('data.urls')),

    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

handler404 = 'common.views.page_not_found'

data/urls.py
from django.urls import path

from . import views

app_name = 'data'

urlpatterns = [
    path('django/', views.data1, name='data/django'),
    path('lotto/', views.data2, name='data/lotto'),
    path('study/', views.data3, name='data/study'),
]

seok/urls.py
from django.urls import path
from django.urls import path

from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'seok' # namespace 앱이 관리하는 독립된 공간

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),            # localhost:8000/pybo/ <- 기본 URL
    path('<int:question_id>/', base_views.detail, name='detail'),                                    # 글 상세 보기

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),                    # 글 생성
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),  # 글 수정
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),  # 글 삭제

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),  # 답변 생성
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),    # 답변 수정
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),    # 답변 삭제

    # comment_views.py
    path('comment/create/question/<int:question_id>/',
         comment_views.comment_create_question, name='comment_create_question'),    # 답변-질문 생성
    path('comment/modify/question/<int:comment_id>/',
         comment_views.comment_modify_question, name='comment_modify_question'),    # 답변-질문 수정
    path('comment/delete/question/<int:comment_id>/',
         comment_views.comment_delete_question, name='comment_delete_question'),    # 답변-질문 삭제
    path('comment/create/answer/<int:answer_id>/',
         comment_views.comment_create_answer, name='comment_create_answer'),        # 답변-질문-답변 생성
    path('comment/modify/answer/<int:comment_id>/',
         comment_views.comment_modify_answer, name='comment_modify_answer'),        # 답변-질문-답변 수정
    path('comment/delete/answer/<int:comment_id>/',
         comment_views.comment_delete_answer, name='comment_delete_answer'),        # 답변-질문-답변 삭제

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),

]

seok/views/base_views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q, Count
from django.shortcuts import render, get_object_or_404

from ..models import Question

import logging
logger = logging.getLogger('seok')

def index(request):
    logger.info("INFO 레벨로 출력")
    """
    seok 목록 출력
    """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준
    sh = request.GET.get('sh', 'ac')  # 검색기준

    # 정렬
    if so == 'recommend':  # 추천순 ( 추천이 제일 많은 순서 )
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':  # 인기순 ( 댓글이 제일 많은 순서 )
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    elif so == 'comm':  # 댓글순 ( 해당 글에 댓글이 제일 많은 순서 )
        question_list = Question.objects.annotate(num_answer=Count('comment')).order_by('-num_answer', '-create_date')
    else:  # recent 최신순 ( 최근 수정, 등록한 순서 )
        question_list = Question.objects.order_by('-create_date')

    # 조회
    # Q 함수에 사용한 subject__icontains 제목에 kw 문자열이 포함되었는지를 의미
    # filter 함수에서 모델 필드에 접근하려면 __ 를 이용하면 됨
    if kw:
        if sh == 'sj':
            question_list = question_list.filter(
                Q(subject__icontains=kw)    # 제목 검색
            ).distinct()
        elif sh == 'ct':
            question_list = question_list.filter(
                Q(content__icontains=kw)    # 내용 검색
            ).distinct()
        elif sh == 'at':
            question_list = question_list.filter(
                Q(author__username__icontains=kw)   # 글쓴이 검색
            ).distinct()
        elif sh == 'aw':
            question_list = question_list.filter(
                Q(answer__content__icontains=kw)  # 댓글 내용 검색
            ).distinct()
        else :
            question_list = question_list.filter(
                Q(subject__icontains=kw) |          # 제목 검색
                Q(content__icontains=kw) |          # 내용 검색
                Q(author__username__icontains=kw) | # 글쓴이 검색
                Q(answer__content__icontains=kw)    # 댓글 내용 검색
                # Q(answer__author__username__icontains=kw)  # 댓글 글쓴이 검색
            ).distinct()  # 중복값 제거


    # 페이징처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주는거
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so, 'sh':sh}

    return render(request, 'seok/question_list.html', context)

@login_required(login_url='common:login')
def detail(request, question_id):
    """
    seok 내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    if bool(request.user):
        question.hit.add(request.user)  # 조회수 증가 처리
    context = {'question': question}
    return render(request, 'seok/question_detail.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>OH DONG WEB</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}
<!--
필드 오류(입력값이 누락되었거나 형식에 맞지 않음)
넌필드 오류(입력값과 관계없이 발생한 오류)
-->

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'seok:index' %}">DONG</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
            </li>
            <li>
                <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                {% endif %}
            </li>
            <li>
                <a class="nav-link" href="{% url 'data:data/django' %}">자료</a>
            </li>
        </ul>
    </div>
</nav>

templates/navbar2.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'seok:index' %}">DONG</a>
    </button>
    <div class="navbar-collapse flex-grow-0">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'seok:index'  %}">홈</a>
            </li>
            {% if user.is_authenticated %}
            <li>
                <a class="nav-link" href="{% url 'data:data/django' %}">장고설치/셋팅</a>
            </li>
            <li>
                <a class="nav-link" href="{% url 'data:data/lotto' %}">로또크롤링</a>
            </li>
            <li>
                <a class="nav-link" href="{% url 'data:data/study' %}">끄적끄적</a>
            </li>
            {% else %}
            <li>
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
            </li>
            <li>
                <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
            </li>
            <li>
                <a class="nav-link" href="{% url 'data:data/django' %}">장고설치/셋팅</a>
            </li>
            <li>
                <a class="nav-link" href="{% url 'data:data/lotto' %}">로또크롤링</a>
            </li>
            <li>
                <a class="nav-link" href="{% url 'data:data/study' %}">끄적끄적</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>